
server:
  port: 8080
#  servlet:
#    context-path: /api
#    encoding:
#      charset: utf-8
#      enable: true
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true


spring:
  h2:
    console:
      enabled: true
      path: /h2-console # console 접속 path
      settings:
        web-allow-others: true # local Host 가 아닌 외부에서 접속 할 때
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create



#  mvc:
#    servlet:
#      load-on-startup: 1
